export const FIGURE = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ullamcorper congue elit. Curabitur ac maximus tellus. Ut rutrum lacinia massa. Nullam blandit nec odio eget ultricies. Praesent sodales, turpis sed hendrerit lacinia, tortor justo viverra massa, porta eleifend augue libero id lectus. Morbi ac orci et est dictum vehicula ut non augue. In porttitor volutpat vulputate. Mauris sed semper lorem. Sed ac sagittis mi. Nulla at commodo ante, at lacinia felis.

Praesent non ex quam. Pellentesque felis velit, auctor eu quam ut, laoreet finibus nibh. Etiam hendrerit libero in augue elementum iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla dapibus tellus non lacinia ultricies. Integer enim felis, pretium vel nisi id, euismod ornare libero. Phasellus aliquet condimentum dolor in finibus. Pellentesque imperdiet eros mauris. Donec eu erat leo. Cras sit amet purus sit amet felis mollis molestie vitae non nunc.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras consequat, mauris ac accumsan laoreet, nisi libero auctor libero, non pharetra massa velit vel nisi. Donec at gravida mi. Quisque augue lacus, ultricies eget accumsan eleifend, cursus vel nunc. Nam placerat tincidunt nibh, id imperdiet ipsum iaculis vestibulum. Sed scelerisque tortor quis vestibulum egestas. Etiam at risus dui. Nullam pharetra facilisis lorem in scelerisque. Nunc et massa vestibulum, dignissim tortor in, bibendum ex. Aenean sit amet ipsum nec neque lacinia faucibus nec nec dui. Cras nec lacinia metus. Praesent est leo, vehicula et lacinia at, dapibus ac nulla. Morbi id ultricies turpis, et scelerisque magna. Cras fermentum ligula nec nulla finibus, quis hendrerit sapien tristique. Etiam lacus sem, fermentum ullamcorper feugiat non, consequat vel tellus.

Sed accumsan in tortor eget molestie. Donec sit amet pulvinar eros. Donec ligula neque, blandit vitae lacus non, ultrices lobortis risus. Duis iaculis dolor eget imperdiet fringilla. Praesent ullamcorper ex sed augue tempus, id auctor mauris mattis. Quisque purus diam, tincidunt eu purus at, laoreet elementum eros. Praesent bibendum hendrerit tellus, id facilisis augue egestas in. Curabitur eu mauris bibendum, porta libero id, condimentum sapien. Ut tincidunt, augue vel viverra sollicitudin, neque sem tristique augue, et lobortis magna metus a justo. Vivamus finibus, purus quis condimentum accumsan, purus nisi scelerisque nulla, quis malesuada elit neque eu arcu.

In at commodo arcu, sit amet congue eros. Quisque mauris turpis, pellentesque in justo quis, luctus pretium nibh. Morbi malesuada lorem quis ipsum venenatis, viverra scelerisque ligula viverra. Suspendisse id convallis lorem. Morbi eu tellus vel erat luctus rhoncus eget ac nunc. Aliquam accumsan suscipit elit, id volutpat purus ultricies at. Nunc diam quam, sagittis ut odio in, interdum maximus elit. Praesent eget magna et neque vestibulum imperdiet nec in sem. Praesent aliquam felis sit amet lobortis rutrum. Mauris odio velit, ornare in rutrum ut, tempus eu sem. Pellentesque id sapien sapien.`;

export const OBJECT_FIGURE = {
	name: 'Leon Kowalski',
	age: 2
};
